import type {Metadata} from 'next';
import {Poppins} from 'next/font/google';
import './style/index.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Creative Catalyst - Dive into the Future',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppins.className} bg-black`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
